### ISSUE TITLE
Generator not respecting name escaping

### ISSUE THREAD

**Issue by westito** [be-hase/protoc-gen-kotlin-ext#14]
Preventing collosion of java keywords the protobuf generator escapes "Class" that not followed by kotlin-ext generator:

Current:
<img width="385" alt="Képernyőfotó 2024-06-18 - 7 37 25" src="https://github.com/be-hase/protoc-gen-kotlin-ext/assets/536799/d84b4e40-c705-42cd-9838-5472ed7327a6">

Correct:
<img width="400" alt="Képernyőfotó 2024-06-18 - 7 37 45" src="https://github.com/be-hase/protoc-gen-kotlin-ext/assets/536799/76809c1b-f751-49be-a4f5-14d78f0a6a29">

**Comment by be-hase** [comment]
Oh, I didn't realize there was such a specification. Thank you for the report.

**Comment by be-hase** [comment]
memo:
- https://docs.oracle.com/javase/specs/jls/se15/html/jls-3.html#jls-3.9
- https://kotlinlang.org/docs/keyword-reference.html#hard-keywords

**Comment by be-hase** [comment]
Fixed and released.
https://central.sonatype.com/artifact/dev.hsbrysk/protoc-gen-kotlin-ext/1.0.1
